name: bmadx
channels:
  - conda-forge
  - pytorch
dependencies:
  - python >=3.10
  - ipython
  - ipykernel
  - pytorch
  - numpy
  - matplotlib
  - pytest
  - numba
  - numdifftools
  - kornia
  - bmad
  - pytao
  - distgen
  - pip
  - pip:
      # Install the bmad-x package as well
      - .
